# Generated by Django 6.0.6 on 2026-07-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xcoin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositwallet',
            name='qr_code',
        ),
    ]
