# Generated by Django 6.0.6 on 2026-07-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcoin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='network',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='txid',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('crypto', 'Crypto'), ('bank', 'Bank')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('investment', 'Investment'), ('buy_asset', 'Buy Asset')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
