# Generated by Django 6.0.6 on 2026-07-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcoin', '0002_remove_depositwallet_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositwallet',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='wallets/'),
        ),
    ]
