# Generated by Django 6.0.6 on 2026-07-21 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcoin', '0002_notification_send_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['rank', 'name']},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='xcoin_trans_user_id_2a06a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='xcoin_trans_status_2d3a01_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='xcoin_trans_transac_779577_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='xcoin_trans_user_id_91b54a_idx',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='is_frozen',
        ),
        migrations.AddField(
            model_name='asset',
            name='ath',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='All Time High'),
        ),
        migrations.AddField(
            model_name='asset',
            name='atl',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='All Time Low'),
        ),
        migrations.AddField(
            model_name='asset',
            name='circulating_supply',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='asset',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='high_24h',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='low_24h',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='asset',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='volume_24h',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AddField(
            model_name='transaction',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xcoin.asset'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='locked_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Funds locked in investments or pending trades', max_digits=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_withdrawal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('crypto', 'Cryptocurrency'), ('stock', 'Stock'), ('forex', 'Forex'), ('commodity', 'Commodity'), ('etf', 'ETF'), ('index', 'Index')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, help_text='24 Hour Percentage Change', max_digits=8),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy'), ('sell', 'Sell'), ('investment', 'Investment'), ('profit', 'Profit'), ('bonus', 'Bonus')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
    ]
