# Generated by Django 6.0.6 on 2026-07-31 17:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xcoin', '0003_depositwallet_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositwallet',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_code'),
        ),
    ]
