# Generated by Django 6.0.6 on 2026-07-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcoin', '0003_alter_asset_options_alter_wallet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='deposit_proofs/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='txid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
