# Generated by Django 6.0.6 on 2026-07-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcoin', '0004_transaction_proof_transaction_txid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
