# Generated by Django 6.0.6 on 2026-07-31 20:36

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcoin', '0006_remove_user_qr_code_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'International Passport'), ('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card")], max_length=30)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('document_front', cloudinary.models.CloudinaryField(max_length=255, verbose_name='document_front')),
                ('document_back', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document_back')),
                ('selfie', cloudinary.models.CloudinaryField(max_length=255, verbose_name='selfie')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
