# Generated by Django 6.0.6 on 2026-07-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcoin', '0007_kycverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycverification',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'KYC Verification', 'verbose_name_plural': 'KYC Verifications'},
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('state_id', 'State ID'), ('government_id', 'Government ID'), ('national_id', 'National ID')], max_length=30),
        ),
    ]
